### ISSUE TITLE
[Proposal] Relaxing gymnasium requirement

### ISSUE THREAD

**Issue by BurakDmb** [isaac-sim/IsaacLab#1002]
### Proposal

Hi, for some other libraries, I am forced to use Gymnasium version 0.29.1.
However, Isaaclab has a 0.29.0 strict requirement.  
https://github.com/isaac-sim/IsaacLab/blob/52af899614318a25404677bd7b754d867e743c45/source/extensions/omni.isaac.lab/setup.py#L29 and https://github.com/isaac-sim/IsaacLab/blob/52af899614318a25404677bd7b754d867e743c45/source/extensions/omni.isaac.lab/config/extension.toml#L26

Can you bump Gymnasium to 0.29.1 or at least relax the requirement to cover both 0.29.0 and 0.29.1

0.29.1 is a minor release and it only adds some small warnings, so I don't think anything will break in IsaacLab.
https://github.com/Farama-Foundation/Gymnasium/releases/tag/v0.29.1

I can open a PR if help is needed.

**Comment by Mayankm96** [comment]
The last time I checked, the video recorder in 0.29.1 was broken. So we reverted to keeping it at 0.29.0. We can relax it but then it becomes hard to ensure that things aren't breaking because other libraries made breaking changes.

**Comment by BurakDmb** [comment]
I suggest a version specifier like this could cover your concerns and flex the version by a little bit. 
I tested in my local setup for pip installation and setup py seems to be working.
Source for specifying range in install_requires: https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires

`"gymnasium >=0.29.0, <=0.29.1"`

**Comment by BurakDmb** [comment]
Hi, I can create a PR for that, or is someone working on this now? 
Do you happen to see any problems with this version suggestion? @Mayankm96 

My suggestion is changing these lines with `"gymnasium >=0.29.0, <=0.29.1"` to support gymnasium versions 0.29.0 and 0.29.1:

https://github.com/isaac-sim/IsaacLab/blob/52af899614318a25404677bd7b754d867e743c45/source/extensions/omni.isaac.lab/setup.py#L29

https://github.com/isaac-sim/IsaacLab/blob/52af899614318a25404677bd7b754d867e743c45/source/extensions/omni.isaac.lab/config/extension.toml#L26

**Comment by Mayankm96** [comment]
Gymnasium 1.0.0 is out. We would work on switching to it.

@Toni-SM for vis.

**Comment by cyhunblr** [comment]
Are there any updates regarding this issue?
