### ISSUE TITLE
[Proposal] Set the environment action space to be the joint range of motion defined in the USD model

### ISSUE THREAD

**Issue by mateoguaman** [isaac-sim/IsaacLab#1010]
### Proposal

The action space of the environment should be the actual valid range of motion of the joint angles assuming that the most common control mode is position control with a PD/ActuatorNet converter to torque. If this is not reasonable or too domain specific, it'd be nice to make these joint limits easy to query. 

### Motivation

With PPO, it is ok for neural network outputs to be unbounded. However, when using off-policy RL methods such as SAC, TD3, DDPG, etc., most implementations assume that the output of the NN is squashed with a tanh (see [SB3](https://github.com/DLR-RM/stable-baselines3/blob/512eea923afad6f6da4bb53d72b6ea4c6d856e59/stable_baselines3/common/off_policy_algorithm.py#L387), [SBX](https://github.com/araffin/sbx/blob/19c85a1fd8fd56437c2f9c1de081889e49554604/sbx/sac/policies.py#L40), [JaxRL](https://github.com/ikostrikov/jaxrl2/blob/8b12c24543e14738974e9296f278aa6184e8fbb1/jaxrl2/agents/sac/sac_learner.py#L120)). It would make it a lot easier and cleaner to re-scale these actions to match the actual joint limits of the actuators if the actual joint limits (rather than unbounded +/- inf or arbitrary +/- 100 as is currently done in the SB3 wrapper) were exposed in the action space. 

### Alternatives

Currently, it seems like neither [ActuatorBase](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/actuators/actuator_base.py) nor [ActuatorBaseCfg](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/actuators/actuator_cfg.py) expose the joint limits set in the USD model. It would be useful if the joint limits could be set or automatically parsed from the USD file so that it is easier to re-scale actions.

### Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)

**Comment by kellyguo11** [comment]
Joint limits are parsed from the USD and available to read and write through the Articulation class. To read, it can be accessed with `articulation._data.joint_limits`.
