### ISSUE TITLE
[Question] Installation of Isaac Sim 2023.1.1 through Omniverse Launcher Exchange Apps

### ISSUE THREAD

**Issue by ge79puv** [isaac-sim/IsaacLab#1014]
Hey there,

I am trying to install Isaac Sim 2023.1.1 through Omniverse Launcher Exchange Apps. However, there is no this version on Omniverse Launcher any more. Could you tell me how to install this version of Isaac Sim?
![image](https://github.com/user-attachments/assets/f5d4da53-7c91-4a65-a97f-77f154671bb1)

Thanks a lot in advance!

BR

**Comment by Mayankm96** [comment]
This issue does not seem related to Isaac Lab.

We recommend posting it on the Isaac Sim forums: https://forums.developer.nvidia.com/c/omniverse/simulation/69
