### ISSUE TITLE
[Bug Report] Apply action for articulation on GPU

### ISSUE THREAD

**Issue by relifeto18** [isaac-sim/IsaacLab#1047]
### Describe the bug

This is a **Isaac Sim** level's problem. Sorry if here is not the right place to post.

I have a simple script to load the Franka robot into the scene and control the joint position, joint velocity and joint effort using the function `apply_action` under the `Articulation` class. The script worked fine when using CPU, However, when I changed to GPU mode, it output me errors, especially when I specified the value of `joint_velocities` and `joint_efforts`.

### Steps to reproduce

Here is the code I use:

```
from isaacsim import SimulationApp
simulation_app = SimulationApp({"headless": True})

import torch
import numpy as np
from omni.isaac.core import World
from omni.isaac.franka import Franka
from omni.isaac.core.utils.types import ArticulationAction

def main():
    device = 'cuda'
    world = World(device='cuda', backend='torch')
    world.scene.add_default_ground_plane()
    franka = world.scene.add(Franka(prim_path="/World/Fancy_Franka", name="fancy_franka"))
    world.reset()
    
    while simulation_app.is_running():
        joint_positions = torch.tensor(np.random.uniform(0.0, 1.0, size=9)).to(device)
        joint_velocities = torch.tensor(np.random.uniform(0.0, 1.0, size=9)).to(device)
        joint_efforts = torch.tensor(np.random.uniform(0.0, 1.0, size=9)).to(device)
        action = ArticulationAction(joint_positions, joint_velocities, joint_efforts)
        
        franka.apply_action(action)
        
        world.step()
    
    simulation_app.close()

if __name__ == "__main__":
    main()
```

When I run the code, I get this error: `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

### System Info

- Isaac Sim Version: [4.2.0.2]

### Potential Solution 

In file `isaacsim/exts/omni.isaac.core/omni/isaac/core/controllers/articulation_controller.py`

At line 75, change from `if joint_velocities[0][i] is None or np.isnan(joint_velocities[0][i]):` to `if joint_velocities[0][i] is None or np.isnan(self._articulation_view._backend_utils.to_numpy(joint_velocities[0][i])):`

At line 84, change from `if joint_efforts[0][i] is None or np.isnan(joint_efforts[0][i]):` to ` joint_efforts[0][i] is None or np.isnan(self._articulation_view._backend_utils.to_numpy(joint_efforts[0][i])):`

After this, my problem solved.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by kellyguo11** [comment]
Thanks for reporting this, we will raise this with the Isaac Sim team.
