### ISSUE TITLE
[Question] Question titleValueError: No contact sensors added to the prim: '/World/envs/env_0/Robot'. This means that no rigid bodies are present under this prim. Please check the prim path.

### ISSUE THREAD

**Issue by AlorithmKing** [isaac-sim/IsaacLab#1053]
### Question

ValueError: No contact sensors added to the prim: '/World/envs/env_0/Robot'. This means that no rigid bodies are present under this prim. Please check the prim path.

how can i solve

**Comment by elle-miller** [comment]
You must specify which rigid bodies under Robot to add the contact sensor to. For example, the panda finger bodies are called `panda_leftfinger`, `panda_rightfinger`, so I did:

```
contact_cfg = ContactSensorCfg(
        prim_path="/World/envs/env_.*/Robot/.*finger", update_period=0.0, history_length=1, debug_vis=True
    )
```

**Comment by kellyguo11** [comment]
Yes, the ContactSensorCfg should specify the prim_path pointing to rigid bodies. An example can be seen [here](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/direct/anymal_c/anymal_c_env.py#L101). Additionally, make sure that `activate_contact_sensors` is set to True in the `RigidObjectSpawnerCfg`.
