### ISSUE TITLE
[Question] Is it possible to change the object after an episode?

### ISSUE THREAD

**Issue by chandramohanjagadeesan** [isaac-sim/IsaacLab#1062]
I am working on a Next best view planning task using Reinforcement learning. I have an object to be scanned and camera moving around the object to scan the object. I want the rl agent to generalise for many object and so I would like to change the object after certain number of episodes. How can I do it? Thanks for the reply

**Comment by garylvov** [comment]
Duplicate https://github.com/isaac-sim/IsaacLab/issues/1063
