### ISSUE TITLE
[Bug Report] docker/container.py enter fails if `DISPLAY` env is not defined

### ISSUE THREAD

**Issue by GiulioRomualdi** [isaac-sim/IsaacLab#1162]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug
I'm trying to enter the container built into a server without display. The `enter` command fails  
as shown above

### Steps to reproduce

I started the container as written in the documentation `python3 docker/container.py start`

Then when I entered the container I got the following error:
```
python3 docker/container.py enter
[INFO] Using container profile: base
[INFO] X11 Forwarding is disabled from the settings in '.container.cfg'
[INFO] X11 forwarding is disabled. No action taken.
[INFO] Entering the existing 'isaac-lab-base' container in a bash session...

Traceback (most recent call last):
  File "/home/iit.local/gromualdi/robot-code/IsaacLab/docker/container.py", line 127, in <module>
    main(args_cli)
  File "/home/iit.local/gromualdi/robot-code/IsaacLab/docker/container.py", line 111, in main
    ci.enter()
  File "/home/iit.local/gromualdi/robot-code/IsaacLab/docker/utils/container_interface.py", line 146, in enter
    f"DISPLAY={os.environ['DISPLAY']}",
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY
```

### System Info

Describe the characteristics of your environment:

- Commit: e00d62561a1b4ab19985bc15b40ac77c10bd5e33 (v1.2.0)
- Isaac Sim Version: `4.2.0-rc.18+release.16044.3b2ed111.gl`
- OS: Ubuntu 22.04
- GPU: NVIDIA A100 80GB PCIe
- CUDA: 12.2
- GPU Driver: 535.183.01

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Make the script running even if the display is not defined

**Comment by GiulioRomualdi** [comment]
https://github.com/isaac-sim/IsaacLab/issues/1163 attempts to solve the issue

**Comment by Dhoeller19** [comment]
Thanks a lot @GiulioRomualdi for the report and the fix!
We'll get this merged asap.
