### ISSUE TITLE
[Question] Is it easy to use WandB with rl_games?

### ISSUE THREAD

**Issue by JunghwanRo** [isaac-sim/IsaacLab#1183]
### Question

I know rsl-rl is already supporting WandB as an option, 

But I remember the previous IsaacGym was supporting it with rl_games as well. 

Can we use WandB as a logger with rl_games? Or does it require significant effort?

**Comment by Mayankm96** [comment]
The RL library handles data logging. There isn't anything we do on that aspect.

The question seems a better fit to ask on the RL-Games repository.
