### ISSUE TITLE
[Bug Report] Environment spacing not proper in direct rl environment using interactivescenecfg

### ISSUE THREAD

**Issue by chandramohanjagadeesan** [isaac-sim/IsaacLab#1256]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

I have used interective scenecfg to produce a scene in direct rl environment. I have many object and 2 robots in the environment. The spawning of the robot takes place properly in the environment at the pos where i want it to be. Se the picture below for reference. In  the reset I am using "self.robot.write_root_pose_to_sim(self.robot.data.default_root_state[env_ids][:, :7], env_ids)". This makes all the robot go to the 0,0,0 position as given in the ArticulationCfg. According to me it must go to the 0,0,0 of the environment not of the world coordinates. 

### Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

![Screenshot from 2024-10-17 14-07-58](https://github.com/user-attachments/assets/9906b2a1-756a-4e34-a9a6-8d1823a2b891)
How the robot spawns after reset

![Screenshot from 2024-10-17 14-29-37](https://github.com/user-attachments/assets/f46faf04-7b61-4f47-b9b3-c654b40ddf93)

How it must spawn

**Comment by Mayankm96** [comment]
You must offset them with env origins as mentioned in the tutorials:

> https://isaac-sim.github.io/IsaacLab/source/tutorials/01_assets/run_rigid_object.html#resetting-the-simulation-state
