### ISSUE TITLE
[Bug Report] Can't link the omniverse assets in training process inside docker container.

### ISSUE THREAD

**Issue by Privilger** [isaac-sim/IsaacLab#1297]
### Describe the bug

Following the [docker deployment tutorial](https://isaac-sim.github.io/IsaacLab/main/source/deployment/docker.html), I was able to run isaacsim inside the docker container with headless mode on a **remote server workstation computer**.

However, when I try to train a G1 walking policy using the following command:
`/isaac-sim/python.sh source/standalone/workflows/rsl_rl/train.py --task Isaac-Velocity-Flat-G1-v0 --num_env 4096 --headless`

I receive this warning and the python program is terminated.
![WXWorkCapture_17290464031799](https://github.com/user-attachments/assets/7147a79c-d9c4-4e46-b03b-73ac5f2b2c43)

### Steps to reproduce

1. Enter the docker container with this [tutorial](https://isaac-sim.github.io/IsaacLab/main/source/deployment/docker.html)

3. run command:
 `/isaac-sim/python.sh source/standalone/workflows/rsl_rl/train.py --task Isaac-Velocity-Flat-G1-v0 --num_env 4096 --headless`

 
 
8. Could not open asset @http://omniverse-content-production....
 ![WXWorkCapture_17290464031799](https://github.com/user-attachments/assets/7147a79c-d9c4-4e46-b03b-73ac5f2b2c43)

### System Info

Describe the characteristic of your environment:

- Commit: a56291d07a28548784f46aed16a4b219c9b57e39
- Isaac Sim Version: 4.2.0
- OS: Ubuntu 20.04
- GPU: RTX L20
- CUDA: 12.2
- GPU Driver: 535

### Additional context

I check my **remote server computer**'s network to see if it is network problem.
I was able to download the asset using 'wget http://omniverse-content-production....' command to download the usd asset successful.

I also try to run the training python script in my **local computer** with docker container, it work well. 

### Checklist

- [x ] I have checked that there is no similar issue in the repo (**required**)
- [ x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by jsmith-bdai** [comment]
Thanks for posting - this is strange. Can you attach a full stack trace please?

**Comment by xiaojuntime** [comment]
# On host side
1. Determine local assets directory by  `$ docker inspect isaac-lab-base`
For instance, using following volume mapping
    host: "/var/lib/docker/volumes/docker_isaac-lab-data/_data"
    container: "/workspace/isaaclab/data_storage"
Then create the local directory structure 
$ sudo mkdir -p /var/lib/docker/volumes/docker_isaac-lab-data/_data/Assets/Isaac/4.2/

2. Download assets to local directory
You can pre-copy/download any assets you want to the local directory.
For 'Isaac-Velocity-Flat-G1-v0' task, following assets are needed.
![image](https://github.com/user-attachments/assets/5e19e300-6795-42e0-963e-ffb29ec145f5)

# In isaac-lab-base container
Change the assets_path in /workspace/isaaclab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py from external website to local asset directory.
        #assets_path = "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2"
        assets_path = "/workspace/isaaclab/data_storage/Assets/Isaac/4.2"

Following command should be ok.
`# /isaac-sim/python.sh source/standalone/workflows/rsl_rl/train.py --task Isaac-Velocity-Flat-G1-v0 --num_env 4096 --headless`

**Comment by Privilger** [comment]
> Thanks for posting - this is strange. Can you attach a full stack trace please?

Hi, thanks for reply, this the the log of the progress
![image](https://github.com/user-attachments/assets/bb623bb3-4c02-427e-9bd5-e56f98fe94e5)

**Comment by Privilger** [comment]
> # On host side
> 1. Determine local assets directory by  `$ docker inspect isaac-lab-base`
>    For instance, using following volume mapping
>    host: "/var/lib/docker/volumes/docker_isaac-lab-data/_data"
>    container: "/workspace/isaaclab/data_storage"
>    Then create the local directory structure
>    $ sudo mkdir -p /var/lib/docker/volumes/docker_isaac-lab-data/_data/Assets/Isaac/4.2/
> 2. Download assets to local directory
>    You can pre-copy/download any assets you want to the local directory.
>    For 'Isaac-Velocity-Flat-G1-v0' task, following assets are needed.
>    ![image](https://private-user-images.githubusercontent.com/865681/380952966-5e19e300-6795-42e0-963e-ffb29ec145f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDQxODUsIm5iZiI6MTczMDgwMzg4NSwicGF0aCI6Ii84NjU2ODEvMzgwOTUyOTY2LTVlMTllMzAwLTY3OTUtNDJlMC05NjNlLWZmYjI5ZWMxNDVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxMDUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmY0ZTY3N2I2MzIzMjg5ZDExZGE4N2M3MzUwYzM1ZDQwYzY0ODljYWQxZGFjMTYxZmQwMmY2N2E0N2EzZjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4D3J9hMu6KDnN_HT1ZSk4abIcsNUGy1FvXwJTOnnXwo)
> 
> # In isaac-lab-base container
> Change the assets_path in /workspace/isaaclab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py from external website to local asset directory. #assets_path = "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2" assets_path = "/workspace/isaaclab/data_storage/Assets/Isaac/4.2"
> 
> Following command should be ok. `# /isaac-sim/python.sh source/standalone/workflows/rsl_rl/train.py --task Isaac-Velocity-Flat-G1-v0 --num_env 4096 --headless`

Thanks for reply. It works well!

**Comment by RandomOakForest** [comment]
It seems you have resolved this issue. Will close it for now. Thanks.
