### ISSUE TITLE
[Bug Report] AttributeError: 'DeformableObject' object has no attribute '_data'. Did you mean: 'data'?

### ISSUE THREAD

**Issue by sabinakaminska95** [isaac-sim/IsaacLab#1298]
When I trying to add different deformable object by adding .stl model and after this trying to run ./isaaclab.sh -p source/standalone/environments/state_machine/lift_teddy_bear.py but with changing .usd with my own object the error is occur:

AttributeError: 'DeformableObject' object has no attribute '_data'. Did you mean: 'data'?

**Comment by chenzyn** [comment]
I got the same error when I call the `write_root_pose_to_sim` method in 'RigidObject' Class.
```
AttributeError: 'RigidObject' object has no attribute '_data'. Did you mean: 'data'?
```

**Comment by Mayankm96** [comment]
Usually the error happened before this popped up. Please check above in the terminal and see what other errors happen before this one.

**Comment by RandomOakForest** [comment]
It seems you may have resolved this issue. Will close it for now. Please post a full error log may we have to investigate this further.
