### ISSUE TITLE
[Bug Report] Incorrect Unit of length in CameraCfg

### ISSUE THREAD

**Issue by Autumnhxp** [isaac-sim/IsaacLab#1318]
### Describe the bug

The unit of focal length and horizontal aperture should be both in mm rather than cm to ensure the accuracy of the results in simulation.

### Steps to reproduce

[source/extensions/omni.isaac.lab/omni/isaac/lab/sim/spawners/sensors/sensors_cfg.py](https://github.com/isaac-sim/IsaacLab/commit/7b3ca4ffe9914203865a4b878325b09720b50236#diff-10d8aeefa5775412e1e5dc1545c7b2104aaf7ac7107bf9afa70eac7b5e31e051)

### System Info

Describe the characteristic of your environment:

- Commit: [7b3ca4f]
- Isaac Sim Version: [4.1.0.0]
- OS: [Ubuntu 20.04]
- GPU: [RTX 4090]
- CUDA: [12.4]
- GPU Driver: [550.107.02]

### Additional context

The focal length of 35mm-50mm is close to the human perspective, 24cm (240mm) is telephoto lens. 

### Checklist

- [ x ] I have checked that there is no similar issue in the repo (**required**)
- [ x ] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

- [ ] Correct the unit in description.

**Comment by jsmith-bdai** [comment]
cc: @pascal-roth, can you confirm this?

**Comment by RandomOakForest** [comment]
Thanks for posting this. The default values for Isaac Lab are in cm and come from [Replicator](https://docs.omniverse.nvidia.com/py/replicator/1.11.16/source/extensions/omni.replicator.core/docs/API.html#cameras). I will forward this note to the Replicator team and close this for now.
