### ISSUE TITLE
[Question] Improving RL Training for Unitree G1: Adding Minimal Height Restriction for Center of Mass

### ISSUE THREAD

**Issue by XinyuSong123** [isaac-sim/IsaacLab#1329]
Hi, I recently conducted RL training with the Unitree G1 on flat terrain. The results show that, while it can move toward the commanded velocity, it struggles to stand up and exhibits a very unusual gait. After checking the reward settings, I found that there is no height restriction for the center of mass (presumably the torso link). Could you provide some guidance on how to add a minimum height restriction for the torso link? Thank you!

**Comment by KyleM73** [comment]
Are you looking for a reward to track a desired center of mass height or a termination condition if the center of mass falls below a certain cutoff height?

**Comment by XinyuSong123** [comment]
> Are you looking for a reward to track a desired center of mass height or a termination condition if the center of mass falls below a certain cutoff height?

Both reward options sound good to me. Additionally, could you provide guidance on implementing a reward that encourages the G1 to lift its legs at a specific frequency? Thank you!!!!

**Comment by XinyuSong123** [comment]
Ah I've found the height settings
