### ISSUE TITLE
Bug Fixed for the fish eye config

### ISSUE THREAD

**Issue by wang59695487** [isaac-sim/IsaacLab#1331]
https://github.com/isaac-sim/IsaacLab/blob/9cc298e938c8903f4ba3d50a222c9c1f3a76c435/source/extensions/omni.isaac.lab/test/sim/test_spawn_sensors.py#L78

The issue originates from the project type in FisheyeCameraCfg(https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/spawners/sensors/sensors_cfg.py#L171). To properly use the API in Isaac Sim Rep, it should be "fisheyePolynomial" rather than variations like "fisheye_polynomial".

   -  fisheye_orthographic -> fisheyeOrthographic
   -  fisheye_equidistant -> fisheyeEquidistant
   - fisheye_equisolid -> fisheyeEquisolid
   - fisheye_polynomial -> fisheyePolynomial
   - fisheye_spherical -> fisheyeSpherical

**Comment by command-z-z** [comment]
You are right! I'm curious why such a big bug has not been fixed. I will raise a PR

**Comment by command-z-z** [comment]
> https://github.com/isaac-sim/IsaacLab/blob/9cc298e938c8903f4ba3d50a222c9c1f3a76c435/source/extensions/omni.isaac.lab/test/sim/test_spawn_sensors.py#L78
> 
> The issue originates from the project type in FisheyeCameraCfg(https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/spawners/sensors/sensors_cfg.py#L171). To properly use the API in Isaac Sim Rep, it should be "fisheyePolynomial" rather than variations like "fisheye_polynomial".
> 
> * fisheye_orthographic -> fisheyeOrthographic
> * fisheye_equidistant -> fisheyeEquidistant
> * fisheye_equisolid -> fisheyeEquisolid
> * fisheye_polynomial -> fisheyePolynomial
> * fisheye_spherical -> fisheyeSpherical

hi, I would like to know how you know the correct camera projection_type parameters. I checked the informations on [Replicator camera](https://docs.omniverse.nvidia.com/py/replicator/1.9.8/source/extensions/omni.replicator.core/docs/API.html#omni.replicator.core.create.camera) website. Only finding the following type, Acttually, `fisheye_polynomial` isn't the correct parameter.
![Screenshot from 2024-10-31 23-15-24](https://github.com/user-attachments/assets/038e9a44-f1f9-4779-a607-7c72b234938f).

**Comment by command-z-z** [comment]
I found that the` projection_type` only supports the following six parameters.
![Screenshot from 2024-10-31 23-29-10](https://github.com/user-attachments/assets/0ee243f7-45f3-47b8-bdcb-601723d5d264)
