### ISSUE TITLE
[Question] How to generate terrains that are uneven and have obstacles at the same time?

### ISSUE THREAD

**Issue by Wang-Haitong** [isaac-sim/IsaacLab#1382]
### Question
Hi,

I'd like to ask what's the best practice to have both rough terrain and obstacles at the same time. I'm currently using `repeated_object_terrain` to create obstacles, but the free space is flat terrain. 
<img width="763" alt="image" src="https://github.com/user-attachments/assets/4c8424ff-8f7f-4e09-9e82-384cbd09e142">

Is there a way to have both rough terrain and obstacles? (something like the below image) 
<img width="230" alt="image" src="https://github.com/user-attachments/assets/a9fd93c8-0344-4ce8-9309-a94207194853">

**Comment by Wang-Haitong** [comment]
I found a workaround, which is to convert the trimesh into height field, add uniform noise to the height field, then convert the height field back to trimesh.
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/0b4762c1-6453-42b4-8525-cd20049ec675">

**Comment by StrainFlow** [comment]
Great Solution! Does this resolve your issue?
