### ISSUE TITLE
Installation using Isaac Sim Binaries reports many errors

### ISSUE THREAD

**Issue by MingchaoQi** [isaac-sim/IsaacLab#1392]
1. When I installed isaac lab in the conda environment according to option 2, the following error occurred when I ran the tutorial in the document. I think there is a problem with the path writing in the isaaclab.sh script, because the /source/extensions folder is in IsaacLab, not the _isaac_sim folder.
![微信图片_20241107163138](https://github.com/user-attachments/assets/ca0a1525-015c-448e-af8b-a2b70c1dcacf)
![微信图片_20241107163313](https://github.com/user-attachments/assets/a9de876c-7b03-45bd-a3e1-d345421be652)

2. When running the example, an error message is displayed saying that the omni.isaac.kit module cannot be found. The same is true after configuring in vscode according to the document. I think there is confusion in the file path of the script, and I request a fix.

- Isaac Sim Version: 4.2.0
- OS: Ubuntu 22.04
- GPU: RTX3090
- CUDA: 12.2
- GPU Driver: 535.183.01

**Comment by RandomOakForest** [comment]
Could you please provide the tutorial you refer to in (1), and the example you mention in (2). Are these the same? Are you able to [verify your Isaac Lab installation](https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/binaries_installation.html#verifying-the-isaac-lab-installation)? Thanks!

**Comment by xinyu-66** [comment]
Hi, I think you need to check your installation with Isaac Sim, the isaac sim path is usually "/home/xx/.local/share/ov/pkg/isaac_sim-*" and Isaac Lab path is usually "/home/xx/.local/share/ov/pkg/isaac_sim-*/IsaacLab"

If you from China,我觉得你仔细看一下Isaac Lab的安装过程吧，一般是把Lab装在Sim文件夹下面，_isaac_sim看起来是你在symbolic link那一步没搞好，你得把_isaac_sim改成你sim的路径，他那里有注释：
For example: ln -s /home/nvidia/.local/share/ov/pkg/isaac-sim-4.2.0 _isaac_sim

**Comment by MingchaoQi** [comment]
Thank you for your answer. I have solved this problem now. I found that it was because I was using the zsh terminal. When I set the default terminal to bash, the installation went smoothly.

**Comment by TedSYt** [comment]
thanks, i solved by using bash too!
