### ISSUE TITLE
Modify the Target Cube to a Local USD Asset in Isaac-Lift-Cube-Franka-v0 Task Using SKRL for RL Training?

### ISSUE THREAD

**Issue by BateCheaterDemon** [isaac-sim/IsaacLab#1466]
I have attempted to modify the cube that needs to be lifted in the **Isaac-Lift-Cube-Franka-v0 task** to a beaker USD model. I made the change in the` joint_pos_env_cfg.py` file located at `IsaacLab\source\extensions\omni.isaac.lab_tasks\omni\isaac\lab_tasks\manager_based\manipulation\lift\config\franka` 
by setting：

![image](https://github.com/user-attachments/assets/8234f3c8-8f6d-4634-97e6-528b1566079d)

However, I also need to modify the "asset_cfg" in the `lift_env_cfg.py` file found at `IsaacLab\source\extensions\omni.isaac.lab_tasks\omni\isaac\lab_tasks\manager_based\manipulation\lift` 
changed like below:

![image](https://github.com/user-attachments/assets/f4004c4a-ca20-4797-b179-cc529aa26d9e)

 for it to work. But I encountered some other issues still.

My main question is, are there more detailed documents related to RL (Reinforcement Learning) that I can study to learn how to use it, as the method I used was discovered through a long period of examining the code and continuous debugging? The existing Isaac Lab documentation on the RL part is quite scarce. Additionally, I have another question: Is there an Isaac Lab communication forum or Discord? The link for the Isaac Sim Discord seems to be broken. I look forward to your reply, thank you!

**Comment by StrainFlow** [comment]
The material in the documentation is what we have as far as documentation goes, but there are also quite a few sample environments you can play. You can find those on this doc page: https://isaac-sim.github.io/IsaacLab/main/source/overview/environments.html

There is also a lively Omniverse community that includes quite a few Isaac Sim and Isaac Lab developers you can find here: 

https://discord.gg/nvidiaomniverse
