### ISSUE TITLE
[Question] Are there any documents for implementing Hierarchical Reinforcement Learning in Isaac Lab?

### ISSUE THREAD

**Issue by H-Hisamichi** [isaac-sim/IsaacLab#1489]
Hello everyone,

I'm learning two Hexapod locomotion-Policy. (Walking-Policy & Rolling-Policy)
I also plan to train a high-level policy to select the optimal locomotion mode based on terrain roughness.
Are there any demo codes or resources in Isaac Lab that could help with this?

Thank you!

**Comment by kellyguo11** [comment]
Hello, you can take a look at the navigation example: https://github.com/isaac-sim/IsaacLab/tree/main/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/navigation
