### ISSUE TITLE
[Question] The problem of image rendering in multi-agent training

### ISSUE THREAD

**Issue by superjuices** [isaac-sim/IsaacLab#1496]
### Question

I found that when the parameter num_envs>1, the sensors of multiple agents can render each other, but they can penetrate each other (rather than collide). I think this will affect the training of the model with vision.
As shown in the picture：
There is actual depth：
![demo](https://github.com/user-attachments/assets/c7b651fd-d614-4a25-ba3d-d37dfca4184e)

Robots can penetrate each other：
![2024-12-04_15-22](https://github.com/user-attachments/assets/0f414e33-5bf9-4b74-ae56-d053d2539881)

Is there any way to not render each other or render but have collisions?
Looking forward to your reply！
#

**Comment by StrainFlow** [comment]
This can be done by making the environment spacing larger than the camera's clipping range.
