### ISSUE TITLE
[Question] What is the unit of `effort_limit` in `ImplicitActuatorCfg()`?

### ISSUE THREAD

**Issue by H-Hisamichi** [isaac-sim/IsaacLab#1523]
Dear All,

Is the unit of `effort_limit` that can be set in `ArticulationCfg()` in Nm? Or do I need to convert from arm length to N?
Thank you!

**Comment by KyleM73** [comment]
For a prismatic joint it will be N, for a revolute joint it will be Nm. It depends on whether the actuator is generating a force or a torque.

**Comment by H-Hisamichi** [comment]
Hello @KyleM73,

Thank you for your response!
I will set it with Nm.
