### ISSUE TITLE
[Proposal] base height reward on rough terrain

### ISSUE THREAD

**Issue by Andy-xiong6** [isaac-sim/IsaacLab#1524]
### Proposal

Modify the base_height_l2 function to support for rough terrain.

### Motivation

During training bipedal robots on the rough terrain, I found the base_height_l2 function does not support, so I modified it.

### Alternatives

To get the "height" of the terrains, I choose the RayCaster sensor because it can get the position of sensor origin in world frame precisely. So it is helpful for us to calculate the target height adjusted by the rough terrain.

### Checklist

- [x ] I have checked that there is no similar issue in the repo (**required**)

**Comment by RandomOakForest** [comment]
Thanks for posting this. We will tag this for consideration by the team.
