### ISSUE TITLE
[Question] How to Elegantly Retrieve the ‘Previous’ of a ‘Previous Action’?

### ISSUE THREAD

**Issue by Andy-xiong6** [isaac-sim/IsaacLab#1547]
### Question

I am implementing this reward during training a bipedal robot for locomotion tasks:

<img width="930" alt="image" src="https://github.com/user-attachments/assets/6fb60f05-ece9-4c15-8a60-ffaab1820587" />

To simplify the implementation, I added a `prev_prev_action` attribute to the `ActionManager` class in **IsaacLab**.

My question is:

- Is there a more elegant way to retrieve the `prev_prev_action` without modifying the `ActionManager` class?

- Or would it be reasonable to raise a PR to add the `prev_prev_action` functionality to **IsaacLab**?

**Comment by KyleM73** [comment]
One "easy" way to do this would be to create a reward term class instead of just a function. Then you can add state to the class to track the prev prev action and update it on each call. I'm not sure if this is necessarily "elegant" but it's less hacky than changing the action manager locally.
