### ISSUE TITLE
[Bug Report] `omni.isaac.orbit.sensors.Camera.__del__()` method does not destroy render product

### ISSUE THREAD

**Issue by jnzhnd** [isaac-sim/IsaacLab#156]
### Describe the bug

I currently have a simulation running where I would like to take an image using a camera after 10 frames or so, and then remove the camera again for performance reasons. When I run the simulation without creating a camera, I'm getting on average around 45 FPS. If I spawn a camera, I get around 30 FPS (which is about as expected). If I then do `camera.__del__()`, the framerate does not recover. I also see that the camera and replicator prims are still present in the stage, however if i also delete those (using omni.isaac.core.utils.prims.delete_prim()), nothing changes.

From my view, this looks like a bug with orbit where it is not destroying the render product of the camera (see [this thread](https://forums.developer.nvidia.com/t/replicator-composer-memory-leak/271204/6?u=_jon)).

In omni.isaac.orbit.sensors.Camera._initialize_impl(), the render product is created like this (on line 366):
```python
render_prod_path = rep.create.render_product(cam_prim_path, resolution=(self.cfg.width, self.cfg.height))
if not isinstance(render_prod_path, str):
    render_prod_path = render_prod_path.path
self._render_product_paths.append(render_prod_path)
```
This does not preserve access to the render product object itself, only to its path.
Otherwise, we could access the render product itself in the `__del__()` method and do `render_product.destroy()` or something similar there, no?

### Steps to reproduce

A reduced version of my simulation script is as follows:
```python
...
camera_cfg = CameraCfg(
        prim_path=None,
        update_period=0,
        height=2048,
        width=2048,
        data_types=["rgb"],
        spawn=sim_utils.PinholeCameraCfg(
            focal_length=24.0, focus_distance=400.0, horizontal_aperture=20.955, clipping_range=(0.1, 1.0e5)
            ),
        )
...
while simulation_app.is_running():
    ...
    if count == 50:
        # Create a camera
        sim.pause()
        camera = Camera(cfg=camera_cfg.replace(prim_path="/Cameras/Cam_0"))
        sim.play()
            
        # Do some simulation steps to init camera
        for _ in range(2):
            sim.step()
                
        # Save camera data (for now, just print cam output)
        print(camera.data.output[0])

        # Remove the camera from existence again
        camera.__del__()
        prim_utils.delete_prim(prim_path="/Cameras")
        prim_utils.delete_prim(prim_path="/Replicator")
    ...
    count += 1
```

### System Info

- Using the devel branch of Orbit
- Commit: [aaab27b](https://github.com/NVIDIA-Omniverse/Orbit/pull/129/commits/aaab27b76a8b849f39ecd383962836da9459f344)
- Isaac Sim Version: 2023.1.0-hotfix.1
- OS: Ubuntu 22.04
- GPU: RTX 3090
- CUDA: 12.0
- GPU Driver: 525.147.05

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Interesting that it didn't show up as an issue in our unit tests where we are destroying and creating the camera for every fixture. Might be because we create a new stage for every test.

Would you be able to send a MR for it? Otherwise, we can also handle that on our side. It seems like a relatively easy fix.
