### ISSUE TITLE
change the orientation of the rigid body

### ISSUE THREAD

**Issue by ZisongXu** [isaac-sim/IsaacLab#169]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

When I tried to add a YCB object into the environment, I can not change the orientation of the cheezit box:

```
cracker_usd_path = f"{ISAAC_NUCLEUS_DIR}/Props/YCB/Axis_Aligned_Physics/003_cracker_box.usd"
prim_utils.create_prim(
        "/World/envs/env_0/Rigid_obj",
        usd_path=cracker_usd_path,
        translation=(0.9, 0, 0.5),
        orientation=(1, 1.57, 0, 0),
)
```

```
Obj_cfg = RigidObjectCfg()
Obj_cfg.meta_info.usd_path = f"{ISAAC_NUCLEUS_DIR}/Props/YCB/Axis_Aligned_Physics/003_cracker_box.usd"
rigid_object = RigidObject(Obj_cfg)
translation = tuple([0, 0, 0.8])
obj_quat = tuple([1, 1, 0, 1])
rigid_object.spawn("/World/Objects/mustard_bottle",translation=translation, orientation=obj_quat)
```

### Steps to reproduce

I want to change the original orientation of that rigid body, and I tried to change the translation and it works; and then when I tried to change the parameter of the orientation, it always (w:1 ,x:0, y:0, z:0) in the simulator.

### System Info

Describe the characteristic of your environment:

- Commit: [e.g. 8f3b9ca]
- Isaac Sim Version: [e.g. 2022.2.0, this can be obtained by `cat ${ISAACSIM_PATH}/VERSION`]
- OS: [e.g. Ubuntu 20.04]
- GPU: [e.g. RTX 2060 Super]
- CUDA: [e.g. 11.4]
- GPU Driver: [e.g. 470.82.01, this can be seen by using `nvidia-smi` command.]

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Closing this issue due to lack of follow-up activity. Please re-open if the issue still persists.
