### ISSUE TITLE
[Bug Report] destination /storage doesn't exist in container

### ISSUE THREAD

**Issue by LarsDoorenbos** [isaac-sim/IsaacLab#192]
### Describe the bug

Following [these](https://github.com/NVIDIA-Omniverse/orbit/blob/963f3045367be3ccdac4f0902ac2103fcbb6070f/docs/source/deployment/cluster.rst#L20) steps to deploy Orbit on a slurm cluster, there is a fatal error in creating the container stating that the destination /storage doesn't exist in container.

### Steps to reproduce

Follow the steps in the [Cluster guide](https://github.com/NVIDIA-Omniverse/orbit/blob/963f3045367be3ccdac4f0902ac2103fcbb6070f/docs/source/deployment/cluster.rst#L20) to run Orbit on a HPC cluster with slurm.

My local machine starts a job on the cluster, which in turn starts the job that builds the apptainer. The container creation fails due to an error with mounting. The log and error from the job that builds the apptainer looks as follows:

```
(run_singularity.py): Called on compute node with arguments
WARNING: nv files may not be bound with --writable
WARNING: By using --writable, Apptainer can't create /storage destination automatically without overlay or underlay
FATAL:   container creation failed: mount hook function failure: mount /var/apptainer/mnt/session/storage->/storage error: while mounting /var/apptainer/mnt/session/storage: destination /storage doesn't exist in container
(run_singularity.py): Return
```

This error is mentioned in some [docs](https://lscsoft.docs.ligo.org/gstlal/installation.html#singularity-container), where the note says to "add directories in the container for each of the bind mounts explicitly", but it is unclear to me how to fix it in this context. 

My `docker/.env` does not specify `/storage` as a path anywhere, only as a prefix: 

```
# Accept the NVIDIA Omniverse EULA by default
ACCEPT_EULA=Y
# NVIDIA Isaac Sim version to use (e.g. 2022.2.1)
ISAACSIM_VERSION=2023.1.0-hotfix.1
# Derived from the default path in the NVIDIA provided Isaac Sim container
DOCKER_ISAACSIM_PATH=/isaac-sim
# Docker user directory - by default this is the root user's home directory
DOCKER_USER_HOME=/root

###
# Cluster specific settings
###

# Docker cache dir for Isaac Sim (has to end on docker-isaac-sim)
# e.g. /cluster/scratch/$USER/docker-isaac-sim
CLUSTER_ISAAC_SIM_CACHE_DIR=/storage/workspaces/a*****/w****/lars/docker-isaac-sim
# Orbit directory on the cluster (has to end on orbit)
# e.g. /cluster/home/$USER/orbit
CLUSTER_ORBIT_DIR=/storage/homefs/l******/orbit
# Cluster login
CLUSTER_LOGIN=*****@****.ch
# Cluster scratch directory to store the SIF file
# e.g. /cluster/scratch/$USER
CLUSTER_SIF_PATH=/storage/workspaces/a*****/w****/lars
# Python executable within orbit directory to run with the submitted job
CLUSTER_PYTHON_EXECUTABLE=source/standalone/tutorials/00_sim/create_empty.py
```

### System Info

Describe the characteristic of your environment:

- Commit: 963f304
- Isaac Sim Version: 2023.1.0-hotfix.1
- OS (cluster): CentOS Linux 7 (Core)
- GPU: RTX 3090
- CUDA: 12.3
- GPU Driver: 545.23.08

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by masoudmoghani** [comment]
@AutonomousHansen would you be able to help with this? Thanks

**Comment by AutonomousHansen** [comment]
@pascal-roth Do you have any ideas here? The only place I can see that a bind mount potentially causing problems is [here](https://github.com/isaac-orbit/orbit/blob/963f3045367be3ccdac4f0902ac2103fcbb6070f/docker/cluster/run_singularity.sh#L70), but the error message is saying that the directory doesn't exist on the container instead of the host?

**Comment by pascal-roth** [comment]
@AutonomousHansen I agree that line is the most probable cause. @LarsDoorenbos, can you ensure that the `logs` directory exists within your orbit directory on the cluster, it won't be synced to it and can be missing the first time you want to run the code.

**Comment by pascal-roth** [comment]
that is clear, `/workspace` is defined within your docker image and cannot be accessed from outside. It is the directory where during the docker build process orbit is copied and installed (see [here](https://github.com/isaac-orbit/orbit/blob/963f3045367be3ccdac4f0902ac2103fcbb6070f/docker/Dockerfile#L29))

Try to comment out the line where logs are bound to the image, then we can be certain if this is causing the issue.

**Comment by LarsDoorenbos** [comment]
Removing the `-B $CLUSTER_ORBIT_DIR/logs:/workspace/orbit/logs:rw \` line still gives the same error.

**Comment by pascal-roth** [comment]
which apptainer version are you using on the cluster?

**Comment by pascal-roth** [comment]
I agree; it seems like a general mounting error. It is difficult to reproduce from our side as we are running `apptainer version 1.2.5-1.el7`.

**Comment by LarsDoorenbos** [comment]
For now, we found a different machine on which to run Orbit. Thanks anyway!
