### ISSUE TITLE
Isaac sim doesn't function normally after installing Orbit 

### ISSUE THREAD

**Issue by Abi-64** [isaac-sim/IsaacLab#194]
I noticed after installing Orbit on Linux, the Isaac Sim doesn't function normally any more, every time I open the Sim I get lots of warnings and errors before opening the GUI, it happens usually after first restart of the computer after installing Orbit, the Orbit works well though, I think it changes something on Isaac Sim during the installation.

**Comment by Mayankm96** [comment]
Maybe it changes some stuff in Isaac Sim Python environment, and some of the extensions that it loads look for the wrong Python packages? Can you also share the log?

We should look into this on our end as well, but probably making a conda environment for Orbit might be safer?

**Comment by Abi-64** [comment]
Thanks Mayan, I create Conda environment when I install the Orbit, following exact procedure you have on the installation guide, after installation everything is okay, but after the first restart when I open the Isaac sim I get more than 100 errors, Isaac sim opens finally but the example menu and another menu is gone.  next time I open the sim I will save the errors to share.

**Comment by Mayankm96** [comment]
Can you share some more details on your system configuration as well as the logs?

**Comment by Mayankm96** [comment]
We saw some "errors" pop out on some systems. The issue seems that when you install orbit extra-dependencies, RL-Games 1.6.1 pulls in psutils==5.9.8 which Omniverse packages aren't able to find. If you install psutils again, it works fine:

```bash
./orbit.sh -p -m pip install psutils
```

Hope that helps!
