### ISSUE TITLE
class omni.isaac.orbit.envs.mdp.commands.commands_cfg.TerrainBasedPose2dCommandCfg

### ISSUE THREAD

**Issue by Nimingez** [isaac-sim/IsaacLab#283]
class omni.isaac.orbit.envs.mdp.commands.commands_cfg.TerrainBasedPose2dCommandCfg
Is this class for specifying a point in the environment for the robotic arm to reach?
How do I know the coordinates of a point on the table?
How can I specify four points on the desktop to form a rectangle and display it?

**Comment by Mayankm96** [comment]
This depends on what you want to do with it. The pose command just gets "flat patches" from the terrain to which the robot can go. It is primarily designed for navigation environments, but you can modify it to fit your needs.

All coordinates are in the world frame. If you need object-centric transformations, you will need to account for that yourself.
