### ISSUE TITLE
[Question] Connection & Difference Between Orbit & Isaac Lab

### ISSUE THREAD

**Issue by ErcBunny** [isaac-sim/IsaacLab#319]
### Question

Hi,

During the 2024 GTC, [Isaac Lab](https://developer.nvidia.com/isaac-sim#isaac-lab) was announced. I wonder what are the connection and difference between Orbit and Isaac Lab, will Orbit be replaced by Isaac Lab? Or is Isaac Lab another experimental project just like its predecessor Isaac Gym?

Thanks for viewing my question.

**Comment by VladimirFokow** [comment]
this info can also be added to the docs in [FAQs](https://isaac-orbit.github.io/orbit/source/setup/faq.html)

**Comment by Dhoeller19** [comment]
This should be solved now :)
