### ISSUE TITLE
Command and Action

### ISSUE THREAD

**Issue by Nimingez** [isaac-sim/IsaacLab#337]
Thank you for you great work！
Robot reach task， reach_env_cfg 
CommadCfg UniformPoseCommand and ActionCfg
I noticed that your command provides the end-effector position, while the policy outputs actions corresponding to joint positions. Where does the process of inverse kinematics take place?

**Comment by zoctipus** [comment]
You can take a look at 
```'source/extensions/omni.isaac.orbit/omni/isaac/orbit/controllers/differential_ik.py'```
method:
```_compute_delta_joint_pos```

The implementation how ik is calculated is there

**Comment by Mayankm96** [comment]
Exactly. The action term we are using there is [DifferentialInverseKinematicsActionCfg](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.envs.mdp.html#omni.isaac.orbit.envs.mdp.actions.actions_cfg.DifferentialInverseKinematicsActionCfg). It converts pose absolute or relative commands to joint commands and applies them into the simulation.
