### ISSUE TITLE
[Question] Vision-based task, camera-based task

### ISSUE THREAD

**Issue by Guanbin-Huang** [isaac-sim/IsaacLab#394]
Does orbit support vision in the loop's task? any example?
e.g. vision in the training loop
or vision in the task for adapting some settings in the SOTA work in the field of embodied AI.

like the following:
https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/omniisaacgymenvs/tasks/cartpole_camera.py

**Comment by Dhoeller19** [comment]
Hi Guanbin,
This is now supported.

**Comment by hutslib** [comment]
@Dhoeller19 ow to run vision-base RL tasks in isaaclab, is there any example?
