### ISSUE TITLE
[Question] Error when using other python package (open3d) in the environment

### ISSUE THREAD

**Issue by ErvinZzz** [isaac-sim/IsaacLab#397]
### Question
When I try to use open3d to process the pointcloud data from the simulation, it raise a bug:

import open3d as o3d
......
from typing_extensions import TypedDict, NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions'

Any one managed to use open3d inside the environment?

**Comment by Mayankm96** [comment]
Can you please provide more details on which version of Isaac Sim, Isaac Lab and open3d you are working with?
