### ISSUE TITLE
[Question] How to check the translated, rotated axis on Isaac Sim?

### ISSUE THREAD

**Issue by cjoattesollo** [isaac-sim/IsaacLab#400]
Hi,

I'm importing my own robot (ex. ur3e) through the URDF Importer. The robot was modeled based on a pre-setted axis which has rotated and translated in the .urdf file. 
But, when checking the link axis, all axes of the links are fixed to the original axes before being modified during the simulation.

Is it possible to check the translated, rotated axis on Isaac Sim?

(I checked with the ee link axis)
![Screencast from 2024년 05월 07일 17시 16분 10초](https://github.com/NVIDIA-Omniverse/orbit/assets/167397487/476f743f-775d-4116-9910-3b27fe3ae724)

**Comment by Mayankm96** [comment]
You can use the FrameTransformer in IsaacLab to visualize the correct frames.
