### ISSUE TITLE
[Bug Report] no module named omni.usd

### ISSUE THREAD

**Issue by Guanbin-Huang** [isaac-sim/IsaacLab#415]
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/30463291/f09b3199-fae8-4ab1-8476-965471db9d8e)
i run the ./orbit.sh -p source/standalone/demos/quadrupeds.py

but i got an error. i googled it. i got , but as you can see below, the simulator launches firstly then everything else. i still don't know why it doens't work.
<img width="881" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/30463291/1952a558-1cb6-408b-acc7-2f40eb9f156b">

**Comment by fyu-bdai** [comment]
Hi Guanbin, 

I had this issue yesterday as well. My issue was traced down to an incompatible isaac_sim version (2023.1.0 hotfix) with the current version of Orbit. The issue should be resolved if you're using isaac sim 2023.1.1.

**Comment by cnalty** [comment]
I had this same issue. The documentation website still has the line in the installation guide

> export ISAACSIM_PATH="${HOME}/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1"

However you need to use isaac_sim-2023.1.1 . There is a warning at the top of the documentation version 2023.1.0 has been dropped, but this line has not been updated
