### ISSUE TITLE
[Bug Report] Docs: Link to explicit actuators implementations examples is broken 

### ISSUE THREAD

**Issue by SantiDiazC** [isaac-sim/IsaacLab#420]
When clicking in the actuators docs for the explicit actuators implementations examples the link is broken ([omni.isaac.orbit.actuators](https://github.com/NVIDIA-Omniverse/orbit/blob/main/docs/source/api/orbit.actuators.html))

Figure bellow:

![Screenshot from 2024-05-17 16-08-14](https://github.com/NVIDIA-Omniverse/orbit/assets/9308405/67ce3950-3d95-427d-a341-c5a55a2bab92)

**Comment by Mayankm96** [comment]
Should be fixed now. Thanks for pointing it out.
