### ISSUE TITLE
Vscode intelligent prompt question

### ISSUE THREAD

**Issue by WSYANGSX** [isaac-sim/IsaacLab#463]
Hi there!
   When I update Omniisaacgym to IsaacLab as office tutorials. I find it can't execute intelligent prompt in vscode about module relative with omni.isaac.lab... . How can i fix this. Thank you for help!
![image](https://github.com/isaac-sim/IsaacLab/assets/99880178/ef6834be-dda5-4ecd-87ce-5ad83a542be0)

**Comment by pxlong** [comment]
+1, i can not do the code navigation after runing **setup_python_env** from https://isaac-sim.github.io/IsaacLab/source/setup/developer.html

**Comment by pxlong** [comment]
@WSYANGSX  hi, i think maybe the keypoint is to add the source/extensions/omni.isaac.lab* to the **python.analysis.extraPaths** in setttings.json in .vscode
![image](https://github.com/isaac-sim/IsaacLab/assets/4568173/38de114d-88f0-45a7-abc5-e2da679725db)

**Comment by WSYANGSX** [comment]
@pxlong Thank you for nice response! I will try it.
