### ISSUE TITLE
[Bug Report] unmatch between root_view and body_view

### ISSUE THREAD

**Issue by JunghwanRo** [isaac-sim/IsaacLab#466]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py
is keep using the _body_physx_view, which does not match with root_physx_view and generates an error when there is more than 1 depth to rigid body prim. 

### Steps to reproduce

Run the standalone demo quadcopter.py, after adding some rigid body prims with deeper depth. 
For example, Robot/base/base_link

```
Prim paths:  ['/World/Drone/Robot_1/rotor_0', '/World/Drone/Robot_1/rotor_1', '/World/Drone/Robot_1/rotor_2', '/World/Drone/Robot_1/rotor_3']
Root view body names:  ['module_1', 'rotor_1', 'module_0', 'module_2', 'rotor_0', 'rotor_2', 'module_3', 'rotor_3']
Body view body names:  ['rotor_0', 'rotor_1', 'rotor_2', 'rotor_3']
Traceback (most recent call last):
  File "/home/julia/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/asset_base.py", line 92, in <lambda>
    lambda event, obj=weakref.proxy(self): obj._initialize_callback(event),
  File "/home/julia/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/asset_base.py", line 255, in _initialize_callback
    self._initialize_impl()
  File "/home/julia/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py", line 847, in _initialize_impl
    self._body_view_ordering = [body_view_body_names.index(name) for name in root_view_body_names]
  File "/home/julia/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/assets/articulation/articulation.py", line 847, in <listcomp>
    self._body_view_ordering = [body_view_body_names.index(name) for name in root_view_body_names]
ValueError: 'module_1' is not in list
```

For more information on this, check: https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

-->

### System Info

Describe the characteristic of your environment:

- Commit: [e.g. 8f3b9ca]
- Isaac Sim Version: [e.g. 2022.2.0, this can be obtained by `cat ${ISAACSIM_PATH}/VERSION`]
- OS: [e.g. Ubuntu 20.04]
- GPU: [e.g. RTX 2060 Super]
- CUDA: [e.g. 11.4]
- GPU Driver: [e.g. 470.82.01, this can be seen by using `nvidia-smi` command.]

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] quadcopter.py could run with deeper rigid body prims

**Comment by Dhoeller19** [comment]
Yes, depth is now supported for rigid body views unfortunately.
