### ISSUE TITLE
Extension template link is invalid

### ISSUE THREAD

**Issue by rokas-bendikas** [isaac-sim/IsaacLab#473]
The extension template link on page https://isaac-sim.github.io/IsaacLab/source/setup/template.html leads to 404.

**Comment by Easternspork** [comment]
Hello, 
I find that the extension template link (https://github.com/isaac-sim/IsaacLab.ext_template) is still invalid, I am wondering why this issue is marked closed.
Thank you

**Comment by GRINGOLOCO7** [comment]
I still can't see the template anywhere
