### ISSUE TITLE
Random seeds and environment creation

### ISSUE THREAD

**Issue by melecmat** [isaac-sim/IsaacLab#489]
Hi!

I found a potential bug. It seems to me that the random seeds does not have an impact on the environment randomization. In my examples I randomize the mass in a startup event (`mdp.add_body_mass`). 

I started printing the randomized weights and they are always different. Is this the desired behavior? I would expect the seeds to be respected here, especially when the documentation of the scripts claims: 'Seed used for the environment'.

**Comment by hojae-io** [comment]
I observe the same issue. Even if the seed is deterministically set to 42, the resulting training curve (i.e. rewards etc..) are different.
Have you figured out how to resolve this issue?

**Comment by hojae-io** [comment]
Maybe you wanna check: https://github.com/isaac-sim/IsaacLab/issues/904

**Comment by Mayankm96** [comment]
Closing this issue as #904 raises the same concerns. The fix is under review: https://github.com/isaac-sim/IsaacLab/pull/940
