### ISSUE TITLE
[Bug Report] Link not working in Docs

### ISSUE THREAD

**Issue by PerFrivik** [isaac-sim/IsaacLab#544]
### Describe the bug

The extension template [link](https://github.com/isaac-sim/IsaacLab.ext_template) on the following page: https://isaac-sim.github.io/IsaacLab/source/setup/template.html sends me to a github page not found.

**Comment by AugustDG** [comment]
Duplicate of #457

**Comment by Mayankm96** [comment]
Closing this issue since it is a duplicate.
