### ISSUE TITLE
[Proposal] Unitree AlienGo addition

### ISSUE THREAD

**Issue by PietroDrd** [isaac-sim/IsaacLab#583]
### Proposal

I would really appreciate to have AlienGo by Unitree Robotics available in IsaacLab. Mainly having its CFG and its assets.
A trained RL policy for walk would be great too, but not so necessary.

### Other

I am doing a RL project on it and i will probably implement both assets, CFGs and i hope a working RL walking policy.
In case my work is successfull i will do a pull request.

Thanks :)

### Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [ ] Accepted / usefull

**Comment by Mayankm96** [comment]
While we'd like to add support to this model, we are currently swamped with many requests.

You can create the asset yourself using the steps here: https://isaac-sim.github.io/IsaacLab/source/how-to/import_new_asset.html

If you can import the asset and set up its configuration for Isaac Lab, we'd be happy to include it in the framework.
