### ISSUE TITLE
[Question]  [Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin]  

### ISSUE THREAD

**Issue by 936769651** [isaac-sim/IsaacLab#589]
### Question

` python source\standalone\tutorials\00_sim\create_empty.py`

I Can open the window normally, but there is an error, how to solve it?thank you.

 [Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.

![image](https://github.com/isaac-sim/IsaacLab/assets/20020809/81f83389-653d-48a7-a7be-d51462e0a85e)

**Comment by Logan1904** [comment]
Have the same problem here.

Followed this installation guide for Windows: https://isaac-sim.github.io/IsaacLab/source/setup/installation/binaries_installation.html

**Comment by Songdada3** [comment]
I also encountered the same problem. Is there any solution?
{2024-07-16 01:00:02  [Warning] [omni.replicator.core.scripts.annotators] Annotator PostProcessDispatch is already registered, overwriting annotator template
2024-07-16 01:00:02  [Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.
2024-07-16 01:00:02  [Warning] [omni.kit.profiler.window] remove _SpanInstance.__lt__ and use insort 'key' arg instead
}

**Comment by bob-021206** [comment]
Following the offical doc from NVIDIA, if you are starting isaac sim on Windows, this error could be ignored. Cited from Errors No.13: https://docs.omniverse.nvidia.com/isaacsim/latest/known_issues.html

**Comment by kellyguo11** [comment]
Yes, this error can be safely ignored.
