### ISSUE TITLE
[Proposal] Submitting training jobs for HPCs using a PBS job scheduler

### ISSUE THREAD

**Issue by shafeef901** [isaac-sim/IsaacLab#599]
### Proposal

Add support for training using IsaacLab on clusters that use PBS job scheduler.

### Motivation

The current example for training on a cluster assumes a **SLURM (Simple Linux Utility for Resource Management)** job scheduler/workload manager. However, **PBS (Portable Batch System)** is another widely adopted job scheduler. I have managed to submit jobs on a PBS job scheduler-based HPC by adapting the existing job submission scripts.

If this feature seems valuable for the community, I would be happy to contribute by giving the option to choose between the two job schedulers and running the appropriate scripts.
 

### Checklist

- [x] Add support for PBS job schedulers

**Comment by Mayankm96** [comment]
Definitely. Would love to extend the support to as many cluster systems as possible :)
