### ISSUE TITLE
[Bug Report] randomize_joint_parameters doesn't work with randomize friction.

### ISSUE THREAD

**Issue by qiayuanl** [isaac-sim/IsaacLab#676]
### Describe the bug

The randomize_joint_parameters can't correctly armature, lower_limit, and upper_limit WITH randomizing friction.

The randomization on joint friction does not affect anything is already reported [here](https://github.com/isaac-sim/IsaacLab/issues/665)

The below property can be randomized correctly without randomizing friction
- armature
- lower_limit
- upper_limit
However, when the event manager has randomize_joint_parameters for friction randomization, they wouldn't work.

### Steps to reproduce

Pick any examples with a well-trained policy. Add a small randomization for lower_limit:

    scale_all_joint_lower_limit = RandTerm(
        func=mdp.randomize_joint_parameters,
        mode="startup",
        params={"asset_cfg": SceneEntityCfg("robot", joint_names=[".*"]),
                "lower_limit_distribution_params": (1.0, 1.01),
                "operation": "scale"},
    )

Play the policy, even if the policy is not trained with randomization, it will still work (for example, the anymal can still follow the velocity command). However, if we add some friction randomization:

    add_all_joint_frictions = RandTerm(
        func=mdp.randomize_joint_parameters,
        mode="startup",
        params={"asset_cfg": SceneEntityCfg("robot", joint_names=[".*"]), "friction_distribution_params": (0., 0.001),
                "operation": "add"},
    )

The policy will not be able to work not matter how small the friction or lower_limit distribute.

### System Info

- Commit: 3f96602eef96a70e680ca184685e7972948c8f40
- Isaac Sim Version: 4.0.0
- OS: Ubuntu 22.04
- GPU: RTX3070
- CUDA: 12.4
- GPU Driver: 535.183.01

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
As mentioned in #665, we are working on fixing this issue.
