### ISSUE TITLE
How to create new task with new robot?

### ISSUE THREAD

**Issue by jih189** [isaac-sim/IsaacLab#716]
Hi. I just start to learn RL recently. Is there any tutorial to explain how to create a new task for different robot? I can't find any doc to give the detail of principles of the whole framework yet.

**Comment by jtigue-bdai** [comment]
I would start by looking at this portion of the documentation:
https://isaac-sim.github.io/IsaacLab/source/tutorials/03_envs/index.html

**Comment by jih189** [comment]
I wrote a document here in my blog. Please let me know if anything is wrong.

https://jih189.github.io/isaaclab

https://jih189.github.io/isaaclab_project
