### ISSUE TITLE
[Question] Stepping without physics simulation

### ISSUE THREAD

**Issue by frederiknolte** [isaac-sim/IsaacLab#720]
Hi, 

I am currently using the Livestreaming Client to view what is going on in my environment. In my code, this connection is not done asynchronously which means that the livestreaming window only updates if I call `world.step(render=True)`. Even when connecting the livestreaming client to the simulation instance, I have to make sure that `world.step(render=True)` is repeatedly called until the livestream is connected. 

Now, I would like to see what is going on in my environment at the very beginning of the simulation and I cannot connect the streaming client fast enough to do so. By the time it connected, the important stuff has already happened because `world.step(render=True)` has to be called all the time when establishing the connection. Is there a way to call `world.step(render=True)` without advancing the physics? I tried setting `step_sim=False` but this also makes the streaming client unable to connect to the simulation.

**Comment by nikepupu** [comment]
world.render()
