### ISSUE TITLE
[Question] Question title

### ISSUE THREAD

**Issue by vvijay-cov** [isaac-sim/IsaacLab#762]
### Question

I'm trying to edit a usd file to remove certain attributes and would like to save the result with the same structure as the original. However, the usd composer tool seems to add an extra layer of hierarchy each time I save a usd file. I've tried to remove it by using "Save as flattnened" and then dragging the actual object up to the top, but I get the error: "Cannot move/rename ancestral prim".

As a workaround, I saved the edited version as a usda and manually removed the layer.

Please let me know how to address this issue or if I'm using the tool incorrectly.

https://github.com/user-attachments/assets/34b2318f-5552-4493-a8d0-e823ed83c180

**Comment by Mayankm96** [comment]
This sounds like an Omniverse question. Please open this issue on the [Developers Forums](https://forums.developer.nvidia.com/c/omniverse/300) for feedback.

Closing the issue as it isn't relevant for Isaac Lab.
