### ISSUE TITLE
[Question] Setup a multi-robot scenario each with its own articulation root

### ISSUE THREAD

**Issue by dhruvkm2402** [isaac-sim/IsaacLab#764]
Hello @Mayankm96, 
I want to a setup a multi-robot kind of a scenario in which I have 2-3 robots but a single RL policy for training (not multi-agent). The only issue is that there will be multiple articulation roots throwing an error.
Do you have any suggestion on how I can implement this in Isaac Lab?

**Comment by dhruvkm2402** [comment]
Hello,
I was able to resolve it by creating a 2nd robot CFG and add it to the scene.

**Comment by Hokite** [comment]
Can you share how to implement multi-robot through isaac lab? I'm trying to learn 2-3 robots at the same time(not multi agent) throughmanipulators.
