### ISSUE TITLE
[Question] How to randomize robot size at runtime for RL training?

### ISSUE THREAD

**Issue by Wang-Haitong** [isaac-sim/IsaacLab#766]
### Question

Hi, I saw example code and API for domain randomization (e.g., physical material, friction, mass, etc). However, I wonder how to randomize the size (e.g., length, width, height) of a robot (or a rigid body) using API at runtime?

**Comment by Mayankm96** [comment]
This is not possible at runtime with GPU-based physics. You can do it at startup though based on #186
