### ISSUE TITLE
[Question] import error of robot_assembler

### ISSUE THREAD

**Issue by Entongsu** [isaac-sim/IsaacLab#767]
Hi, 

I tried to import the robot assembler but got the error of  
`ModuleNotFoundError: No module named 'omni.isaac.robot_assembler'`

I am wondering if there is any way to import that. Thank you!

**Comment by SantiDiazC** [comment]
Hi @Entongsu ,

The solution to this  was shared on a previous issue [#405](https://github.com/isaac-sim/IsaacLab/issues/405#issuecomment-2179982296),  hope it solves your problem!
