### ISSUE TITLE
[Question] I would like to inquire about the release schedule of AutoMate

### ISSUE THREAD

**Issue by XiangdongHe** [isaac-sim/IsaacLab#822]
Thank you for the high-quality open-source code.

In this article, it is mentioned that **AutoMate** will be integrated into NVIDIA Isaac Lab. Is there currently a plan for this? If so, when will the integration work start approximately?

blog url: https://developer.nvidia.com/blog/training-sim-to-real-transferable-robotic-assembly-skills-over-diverse-geometries/?linkId=100000272950370

**Comment by Cheney-36** [comment]
我也很关注这个项目的集成进展

**Comment by Jendker** [comment]
I'm not sure if you are aware but the code was already released: https://github.com/isaac-sim/IsaacGymEnvs/blob/automate/docs/automate.md
