### ISSUE TITLE
[Question] How to implement pick and place funciton of the Franka robot arm in isaac lab?

### ISSUE THREAD

**Issue by hahans** [isaac-sim/IsaacLab#834]
### Question

How to implement pick and place funciton of the Franka robot arm in isaac lab?In isaac sim, there are examples of pick and place,but how to do it again through the API in isaac lab.

**Comment by Mayankm96** [comment]
We do have examples of state machines in Warp that do batch execution of skills while the environment is using a Differential-IK controller.

> https://github.com/isaac-sim/IsaacLab/blob/main/source/standalone/environments/state_machine/lift_cube_sm.py

Does this help?

**Comment by hahans** [comment]
> We do have examples of state machines in Warp that do batch execution of skills while the environment is using a Differential-IK controller.
> 
> > https://github.com/isaac-sim/IsaacLab/blob/main/source/standalone/environments/state_machine/lift_cube_sm.py
> 
> Does this help?
