### ISSUE TITLE
[Question] How to get timestamp of the data? Is it directly related to physics dt?

### ISSUE THREAD

**Issue by dhruvkm2402** [isaac-sim/IsaacLab#836]
### Question
 Hello,
I have an RL based task and I want to collect data at 10 Hz.
My question is that how do I get timestamp of the data like in ROS? In my case, physics dt is 1/200 and decimation is 20. If my understanding is correct, the actions are being applied at 10 Hz. Similarly, If I'm collecting the data after the pre-physics step, Is it collecting the data at 10 Hz or at every simulation step?

**Comment by Mayankm96** [comment]
You can get the episode length from the buffers and multiply that with `dt` to get the current "time-stamp" of the episode.

Does this answer your question?

**Comment by dhruvkm2402** [comment]
Oh yes. That answers my question. 
Thank you for your help.
