### ISSUE TITLE
[Question] Always fail in registering my own designed environment

### ISSUE THREAD

**Issue by hahans** [isaac-sim/IsaacLab#837]
Always fail in registering my own designed environment.I copied the isaac_tasks file structure to write setup.py,__init__.py and other files, and then used pip install-e, but when I used random_agent.py to run my own designed environment, there was still an error.
![Screenshot from 2024-08-16 12-43-24](https://github.com/user-attachments/assets/ec74ec39-141c-41ff-8203-d0cd9e86264f)

**Comment by Mayankm96** [comment]
Where did you add your environment? In the `lab_tasks` extension or your own separate extension?

If it is the latter, you need to call import so that the tasks from that python module gets registered to Gym.

> https://github.com/isaac-sim/IsaacLab/blob/main/source/standalone/environments/random_agent.py#L35

**Comment by hahans** [comment]
> Where did you add your environment? In the `lab_tasks` extension or your own separate extension?
> 
> If it is the latter, you need to call import so that the tasks from that python module gets registered to Gym.
> 
> > https://github.com/isaac-sim/IsaacLab/blob/main/source/standalone/environments/random_agent.py#L35
it was added in my own separate extension, and I also call the import when I run random_agent.py
 
![Screenshot from 2024-08-16 14-36-05](https://github.com/user-attachments/assets/bb3b05bd-bc06-4feb-9cd4-a7707d589d51)
But it 
didn't work

**Comment by hahans** [comment]
I fixed my issue.A low-level error in the writing of the Cfg code in the environment caused the registration failure of the environment
