### ISSUE TITLE
Tutorial required for ROS2 Implementation of manipulator using Isaaclab

### ISSUE THREAD

**Issue by SakethTecholution** [isaac-sim/IsaacLab#922]
In Isaac sim we have possibility of using omnigraph or using these for standalone scripts , how can we implement the same with Isaac lab

**Comment by SakethTecholution** [comment]
@Mayankm96 
Can u please help me out in this

**Comment by SakethTecholution** [comment]
@animesh-garg

**Comment by Mayankm96** [comment]
You can check the example script in Isaac Sim to see how to use OmniGraph in standalone scripts: 

```
./isaaclab.sh -p ~/IsaacLab/_isaac_sim/standalone_examples/api/omni.isaac.core/omnigraph_triggers.py
```

**Comment by SakethTecholution** [comment]
thank you @Mayankm96
