### ISSUE TITLE
Robocase in Isaac lab

### ISSUE THREAD

**Issue by LinJianjie** [isaac-sim/IsaacLab#923]
### Question
i just saw the webpage https://nvidianews.nvidia.com/news/nvidia-accelerates-worldwide-humanoid-robotics-development, 
saying you can use the Robocasa NIM microservice in [Isaac Lab](https://developer.nvidia.com/blog/fast-track-robot-learning-in-simulation-using-nvidia-isaac-lab/), a framework for robot learning, to generate experiences to retrain the robot model.
Robocasa is implemented on the Robotsuite. 
thereore I would like to ask how to use Robocasa insider isaac lab?

**Comment by kellyguo11** [comment]
We are actively working on integrating Robocasa to Isaac Lab. Please stay tuned for future releases.

**Comment by owenonline** [comment]
Has this been added yet?
