### ISSUE TITLE
[Question] Timeline for full rendering for TiledCamera 

### ISSUE THREAD

**Issue by elle-miller** [isaac-sim/IsaacLab#950]
### Question

In issue #493, Kelly mentioned that you are working on full rendering with the tiled camera:

> Currently, the RGB tiled rendering API only provides ambient RGB, which does not capture any lighting and shadow information. We are working on a full tiled rendering API that will provide the same data as what we would achieve with the renderer.

Can we get an approximate estimate for when this feature may be available? 

I am doing research with pixel-based agents where lighting/shadows can be very important, so would really appreciate any info you can provide. Thank you! :)

**Comment by jtigue-bdai** [comment]
@Dhoeller19 can we provide the estimated release of the full rendering TiledCamera

**Comment by elle-miller** [comment]
![lift](https://github.com/user-attachments/assets/1b07a72d-687b-4ab4-af4d-36af0820b209)

Thank you! :100:
