### ISSUE TITLE
[Question] Pausing simulation to inspect various properties in IsaacSim

### ISSUE THREAD

**Issue by dxyy1** [isaac-sim/IsaacLab#968]
### Question
Hi, there,
This may be a stupid question but if we launch isaacSim through `train.py` like shown below, is it possible to pause the simulation through the IsaacSim GUI? If yes, is it possible to use the GUI to inspect various properties in the simulation?
```
from omni.isaac.lab.app import AppLauncher

# launch omniverse app
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app
```

**Comment by pascal-roth** [comment]
Hi,
yes that is possible. You can pause the simulation in the GUI and then inspect different properties. However, be aware that we deploy fabric to improve the speed so not all aspects will be updated in the GUI.
