### ISSUE TITLE
[Question] curriculum terrain levels not working 

### ISSUE THREAD

**Issue by shendredm** [isaac-sim/IsaacLab#969]
I'm running provided example of rsl_rl for Anymal-C robot in rough terrain environment with curriculum setting as terrain levels , but I can see that generated terrain is transposed and robot spawned on all terrains even if I have set the max_init_terrain_level=1.  
As per my understanding when curriculum is active the terrain levels are labelled as per sequence of sub terrains in  TerrainGeneratorCfg. 

terrain = TerrainImporterCfg(
        prim_path="/World/ground",
        terrain_type="generator",
        terrain_generator=ROUGH_TERRAINS_CFG,
        max_init_terrain_level=1,
        collision_group=-1,
        physics_material=sim_utils.RigidBodyMaterialCfg(
            friction_combine_mode="multiply",
            restitution_combine_mode="multiply",
            static_friction=1.0,
            dynamic_friction=1.0,
        ),
        visual_material=sim_utils.MdlFileCfg(
            mdl_path=f"{ISAACLAB_NUCLEUS_DIR}/Materials/TilesMarbleSpiderWhiteBrickBondHoned/TilesMarbleSpiderWhiteBrickBondHoned.mdl",
            project_uvw=True,
            texture_scale=(0.25, 0.25),
        ),
        debug_vis=False,

ROUGH_TERRAINS_CFG = TerrainGeneratorCfg(
    size=(8.0, 8.0),
    border_width=20.0,
    num_rows=10,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        "pyramid_stairs": terrain_gen.MeshPyramidStairsTerrainCfg(
            proportion=0.2,
            step_height_range=(0.05, 0.23),
            step_width=0.3,
            platform_width=3.0,
            border_width=1.0,
            holes=False,
        ),
        "pyramid_stairs_inv": terrain_gen.MeshInvertedPyramidStairsTerrainCfg(
            proportion=0.2,
            step_height_range=(0.05, 0.23),
            step_width=0.3,
            platform_width=3.0,
            border_width=1.0,
            holes=False,
        ),
        "boxes": terrain_gen.MeshRandomGridTerrainCfg(
            proportion=0.2, grid_width=0.45, grid_height_range=(0.05, 0.2), platform_width=2.0
        ),
        "random_rough": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=0.2, noise_range=(0.02, 0.10), noise_step=0.02, border_width=0.25
        ),
        "hf_pyramid_slope": terrain_gen.HfPyramidSlopedTerrainCfg(
            proportion=0.1, slope_range=(0.0, 0.4), platform_width=2.0, border_width=0.25
        ),
        "hf_pyramid_slope_inv": terrain_gen.HfInvertedPyramidSlopedTerrainCfg(
            proportion=0.1, slope_range=(0.0, 0.4), platform_width=2.0, border_width=0.25
        ),
    },
)

- Isaac Sim Version: [e.g. 4.0, this can be obtained by `cat ${ISAACSIM_PATH}/VERSION`]
- OS: [e.g. Ubuntu 22.04]
![Screenshot from 2024-09-10 20-01-46](https://github.com/user-attachments/assets/1d756684-dbc6-4174-81de-6a4f693c7d13)

- GPU: [e.g. RTX 4060 Super]
- CUDA: [e.g. 12.3]
- GPU Driver: [e.g. 535.183.01]

**Comment by Alkrick** [comment]
The curriculum attribute of your terrain generator should be set to True, it defaults to False, this can be set in the post_init of the EnvCfg class as such: 
![image](https://github.com/user-attachments/assets/7fb4f49c-c32e-4b88-8a7c-646d38af9e79)

**Comment by shendredm** [comment]
Thanks

**Comment by shendredm** [comment]
I thought curriculum is entire terrain region and terrain levels are the no of sub terrain. Example - Flat, slope,rough, stairs. But upon reviewing I found that levels are based upon no of rows and curriculum is for each sub terrain. If we select slope terrain then sub-terrains generated from min slope to maximum slope from given range.
