### ISSUE TITLE
[Question] distance_to_camera to point cloud

### ISSUE THREAD

**Issue by Entongsu** [isaac-sim/IsaacLab#983]
Hi, 

I am wondering how to convert the distance_to_camera to the point cloud. Could you give me some tips on that and is it possible to use the pointcloud annotator in the isaaclab?  Thank you.

**Comment by glvov-bdai** [comment]
Hi,

Shameless plug; I am currently working on a tutorial to make this a little clearer.

This is a work in progress, but it does show how to convert from the distance_to_camera to pointcloud 

https://github.com/isaac-sim/IsaacLab/pull/976
